language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_features:
    - rust: nightly

script:
  - cargo build --verbose --all
  - cargo test  --verbose --all

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  ls -l &&
  ls -l kcov-build &&
  ls -l kcov-build/usr &&
  ls -l kcov-build/usr/local &&
  ls -l kcov-build/usr/local/bin &&
  for file in target/debug/reed-solomon-erasure-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
