[package]
name = "reed-solomon-erasure"
version = "0.9.0"
authors = ["Darren Ldl <darrenldldev@gmail.com>"]
build   = "build.rs"
exclude = [
    "Backblaze_JavaReedSolomon",
    "KlausPost_reedsolomon",
]

[dependencies]
rand = "0.3"
